const localhost = `http://localhost:3002/api`
const serverEndpoint = `https://api.iwcn.top/api`
const domain = localhost;

export const admin_login_url = `${domain}/admin/login`
export const verify_admin_url = `${domain}/admin/verify`
export const get_admin_permissions = `${domain}/admin/get-permissions`
export const insert_company_url = `${domain}/admin/insert-company`
export const get_all_companies = `${domain}/admin/get_companies`
export const get_company_logo = `${domain}/admin/get_company_logo`
export const get_company_by_status = `${domain}/admin/get_company_by_status`
export const get_all_states = `${domain}/admin/get_states`
export const get_company_details = `${domain}/admin/get_company`
export const update_company_url = `${domain}/admin/update_company`
export const delete_company_url = `${domain}/admin/delete_company`
export const get_states_url = `${domain}/admin/get_states`
export const create_staff_url = `${domain}/admin/create_staff`
export const get_staff_list_url = `${domain}/admin/get_staff_list`
export const delete_staff_url = `${domain}/admin/delete_staff`
export const update_admin_url = `${domain}/admin/update_staff`
export const update_password_url = `${domain}/admin/update_password`
export const update_email_url = `${domain}/admin/update_email`
export const get_site_settings_url = `${domain}/admin/get_site_settings`
export const update_site_settings_url = `${domain}/admin/update_site_settings`
export const update_states_url = `${domain}/admin/update_states`
export const get_logo_url = `${domain}/admin/get_logo`
export const get_settings_logo = `${domain}/admin/get_settings_logo`
export const update_settings_logo_url = `${domain}/admin/update_settings_logo`
export const get_twilio_settings = `${domain}/admin/get_twilio_settings`
export const update_twilio_settings = `${domain}/admin/update_twilio_credentials`
export const update_flight_stats = `${domain}/admin/update_flight_stats`
export const get_flight_stats_url = `${domain}/admin/get_flight_stats`
export const get_check_number = `${domain}/admin/get_check_number`
export const update_check_number = `${domain}/admin/update_check_number`
export const get_countries = `${domain}/admin/get_countries`