const countries = [
    { id: 1, countryName: 'Afghanistan' },
    { id: 2, countryName: 'Albania' },
    { id: 3, countryName: 'Algeria' },
    { id: 4, countryName: 'Andorra' },
    { id: 5, countryName: 'Angola' },
    { id: 6, countryName: 'Antigua and Barbuda' },
    { id: 7, countryName: 'Argentina' },
    { id: 8, countryName: 'Armenia' },
    { id: 9, countryName: 'Australia' },
    { id: 10, countryName: 'Austria' },
    { id: 11, countryName: 'Azerbaijan' },
    { id: 12, countryName: 'Bahamas' },
    { id: 13, countryName: 'Bahrain' },
    { id: 14, countryName: 'Bangladesh' },
    { id: 15, countryName: 'Barbados' },
    { id: 16, countryName: 'Belarus' },
    { id: 17, countryName: 'Belgium' },
    { id: 18, countryName: 'Belize' },
    { id: 19, countryName: 'Benin' },
    { id: 20, countryName: 'Bhutan' },
    { id: 21, countryName: 'Bolivia' },
    { id: 22, countryName: 'Bosnia and Herzegovina' },
    { id: 23, countryName: 'Botswana' },
    { id: 24, countryName: 'Brazil' },
    { id: 25, countryName: 'Brunei' },
    { id: 26, countryName: 'Bulgaria' },
    { id: 27, countryName: 'Burkina Faso' },
    { id: 28, countryName: 'Burundi' },
    { id: 29, countryName: 'Cabo Verde' },
    { id: 30, countryName: 'Cambodia' },
    { id: 31, countryName: 'Cameroon' },
    { id: 32, countryName: 'Canada' },
    { id: 33, countryName: 'Central African Republic' },
    { id: 34, countryName: 'Chad' },
    { id: 35, countryName: 'Chile' },
    { id: 36, countryName: 'China' },
    { id: 37, countryName: 'Colombia' },
    { id: 38, countryName: 'Comoros' },
    { id: 39, countryName: 'Congo' },
    { id: 40, countryName: 'Costa Rica' },
    { id: 41, countryName: 'Croatia' },
    { id: 42, countryName: 'Cuba' },
    { id: 43, countryName: 'Cyprus' },
    { id: 44, countryName: 'Czech Republic' },
    { id: 45, countryName: 'Democratic Republic of the Congo' },
    { id: 46, countryName: 'Denmark' },
    { id: 47, countryName: 'Djibouti' },
    { id: 48, countryName: 'Dominica' },
    { id: 49, countryName: 'Dominican Republic' },
    { id: 50, countryName: 'East Timor (Timor-Leste)' },
    { id: 51, countryName: 'Ecuador' },
    { id: 52, countryName: 'Egypt' },
    { id: 53, countryName: 'El Salvador' },
    { id: 54, countryName: 'Equatorial Guinea' },
    { id: 55, countryName: 'Eritrea' },
    { id: 56, countryName: 'Estonia' },
    { id: 57, countryName: 'Eswatini' },
    { id: 58, countryName: 'Ethiopia' },
    { id: 59, countryName: 'Fiji' },
    { id: 60, countryName: 'Finland' },
    { id: 61, countryName: 'France' },
    { id: 62, countryName: 'Gabon' },
    { id: 63, countryName: 'Gambia' },
    { id: 64, countryName: 'Georgia' },
    { id: 65, countryName: 'Germany' },
    { id: 66, countryName: 'Ghana' },
    { id: 67, countryName: 'Greece' },
    { id: 68, countryName: 'Grenada' },
    { id: 69, countryName: 'Guatemala' },
    { id: 70, countryName: 'Guinea' },
    { id: 71, countryName: 'Guinea-Bissau' },
    { id: 72, countryName: 'Guyana' },
    { id: 73, countryName: 'Haiti' },
    { id: 74, countryName: 'Honduras' },
    { id: 75, countryName: 'Hungary' },
    { id: 76, countryName: 'Iceland' },
    { id: 77, countryName: 'India' },
    { id: 78, countryName: 'Indonesia' },
    { id: 79, countryName: 'Iran' },
    { id: 80, countryName: 'Iraq' },
    { id: 81, countryName: 'Ireland' },
    { id: 82, countryName: 'Israel' },
    { id: 83, countryName: 'Italy' },
    { id: 84, countryName: 'Ivory Coast' },
    { id: 85, countryName: 'Jamaica' },
    { id: 86, countryName: 'Japan' },
    { id: 87, countryName: 'Jordan' },
    { id: 88, countryName: 'Kazakhstan' },
    { id: 89, countryName: 'Kenya' },
    { id: 90, countryName: 'Kiribati' },
    { id: 91, countryName: 'Kosovo' },
    { id: 92, countryName: 'Kuwait' },
    { id: 93, countryName: 'Kyrgyzstan' },
    { id: 94, countryName: 'Laos' },
    { id: 95, countryName: 'Latvia' },
    { id: 96, countryName: 'Lebanon' },
    { id: 97, countryName: 'Lesotho' },
    { id: 98, countryName: 'Liberia' },
    { id: 99, countryName: 'Libya' },
    { id: 100, countryName: 'Liechtenstein' },
    { id: 101, countryName: 'Lithuania' },
    { id: 102, countryName: 'Luxembourg' },
    { id: 103, countryName: 'Madagascar' },
    { id: 104, countryName: 'Malawi' },
    { id: 105, countryName: 'Malaysia' },
    { id: 106, countryName: 'Maldives' },
    { id: 107, countryName: 'Mali' },
    { id: 108, countryName: 'Malta' },
    { id: 109, countryName: 'Marshall Islands' },
    { id: 110, countryName: 'Mauritania' },
    { id: 111, countryName: 'Mauritius' },
    { id: 112, countryName: 'Mexico' },
    { id: 113, countryName: 'Micronesia' },
    { id: 114, countryName: 'Moldova' },
    { id: 115, countryName: 'Monaco' },
    { id: 116, countryName: 'Mongolia' },
    { id: 117, countryName: 'Montenegro' },
    { id: 118, countryName: 'Morocco' },
    { id: 119, countryName: 'Mozambique' },
    { id: 120, countryName: 'Myanmar (Burma)' },
    { id: 121, countryName: 'Namibia' },
    { id: 122, countryName: 'Nauru' },
    { id: 123, countryName: 'Nepal' },
    { id: 124, countryName: 'Netherlands' },
    { id: 125, countryName: 'New Zealand' },
    { id: 126, countryName: 'Nicaragua' },
    { id: 127, countryName: 'Niger' },
    { id: 128, countryName: 'Nigeria' },
    { id: 129, countryName: 'North Korea' },
    { id: 130, countryName: 'North Macedonia (formerly Macedonia)' },
    { id: 131, countryName: 'Norway' },
    { id: 132, countryName: 'Oman' },
    { id: 133, countryName: 'Pakistan' },
    { id: 134, countryName: 'Palau' },
    { id: 135, countryName: 'Palestine' },
    { id: 136, countryName: 'Panama' },
    { id: 137, countryName: 'Papua New Guinea' },
    { id: 138, countryName: 'Paraguay' },
    { id: 139, countryName: 'Peru' },
    { id: 140, countryName: 'Philippines' },
    { id: 141, countryName: 'Poland' },
    { id: 142, countryName: 'Portugal' },
    { id: 143, countryName: 'Qatar' },
    { id: 144, countryName: 'Romania' },
    { id: 145, countryName: 'Russia' },
    { id: 146, countryName: 'Rwanda' },
    { id: 147, countryName: 'Saint Kitts and Nevis' },
    { id: 148, countryName: 'Saint Lucia' },
    { id: 149, countryName: 'Saint Vincent and the Grenadines' },
    { id: 150, countryName: 'Samoa' },
    { id: 151, countryName: 'San Marino' },
    { id: 152, countryName: 'Sao Tome and Principe' },
    { id: 153, countryName: 'Saudi Arabia' },
    { id: 154, countryName: 'Senegal' },
    { id: 155, countryName: 'Serbia' },
    { id: 156, countryName: 'Seychelles' },
    { id: 157, countryName: 'Sierra Leone' },
    { id: 158, countryName: 'Singapore' },
    { id: 159, countryName: 'Slovakia' },
    { id: 160, countryName: 'Slovenia' },
    { id: 161, countryName: 'Solomon Islands' },
    { id: 162, countryName: 'Somalia' },
    { id: 163, countryName: 'South Africa' },
    { id: 164, countryName: 'South Korea' },
    { id: 165, countryName: 'South Sudan' },
    { id: 166, countryName: 'Spain' },
    { id: 167, countryName: 'Sri Lanka' },
    { id: 168, countryName: 'Sudan' },
    { id: 169, countryName: 'Suriname' },
    { id: 170, countryName: 'Sweden' },
    { id: 171, countryName: 'Switzerland' },
    { id: 172, countryName: 'Syria' },
    { id: 173, countryName: 'Taiwan' },
    { id: 174, countryName: 'Tajikistan' },
    { id: 175, countryName: 'Tanzania' },
    { id: 176, countryName: 'Thailand' },
    { id: 177, countryName: 'Togo' },
    { id: 178, countryName: 'Tonga' },
    { id: 179, countryName: 'Trinidad and Tobago' },
    { id: 180, countryName: 'Tunisia' },
    { id: 181, countryName: 'Turkey' },
    { id: 182, countryName: 'Turkmenistan' },
    { id: 183, countryName: 'Tuvalu' },
    { id: 184, countryName: 'Uganda' },
    { id: 185, countryName: 'Ukraine' },
    { id: 186, countryName: 'United Arab Emirates (UAE)' },
    { id: 187, countryName: 'United Kingdom (UK)' },
    { id: 188, countryName: 'United States of America (USA)' },
    { id: 189, countryName: 'Uruguay' },
    { id: 190, countryName: 'Uzbekistan' },
    { id: 191, countryName: 'Vanuatu' },
    { id: 192, countryName: 'Vatican City (Holy See)' },
    { id: 193, countryName: 'Venezuela' },
    { id: 194, countryName: 'Vietnam' },
    { id: 195, countryName: 'Yemen' },
    { id: 196, countryName: 'Zambia' },
    { id: 197, countryName: 'Zimbabwe' }
];

module.exports = countries