const states = [
    { id: 1, stateName: 'Alabama' },
    { id: 2, stateName: 'Alaska' },
    { id: 3, stateName: 'Arizona' },
    { id: 4, stateName: 'Arkansas' },
    { id: 5, stateName: 'California' },
    { id: 6, stateName: 'Colorado' },
    { id: 7, stateName: 'Connecticut' },
    { id: 8, stateName: 'Delaware' },
    { id: 9, stateName: 'Florida' },
    { id: 10, stateName: 'Georgia' },
    { id: 11, stateName: 'Hawaii' },
    { id: 12, stateName: 'Idaho' },
    { id: 13, stateName: 'Illinois' },
    { id: 14, stateName: 'Indiana' },
    { id: 15, stateName: 'Iowa' },
    { id: 16, stateName: 'Kansas' },
    { id: 17, stateName: 'Kentucky' },
    { id: 18, stateName: 'Louisiana' },
    { id: 19, stateName: 'Maine' },
    { id: 20, stateName: 'Maryland' },
    { id: 21, stateName: 'Massachusetts' },
    { id: 22, stateName: 'Michigan' },
    { id: 23, stateName: 'Minnesota' },
    { id: 24, stateName: 'Mississippi' },
    { id: 25, stateName: 'Missouri' },
    { id: 26, stateName: 'Montana' },
    { id: 27, stateName: 'Nebraska' },
    { id: 28, stateName: 'Nevada' },
    { id: 29, stateName: 'New Hampshire' },
    { id: 30, stateName: 'New Jersey' },
    { id: 31, stateName: 'New Mexico' },
    { id: 32, stateName: 'New York' },
    { id: 33, stateName: 'North Carolina' },
    { id: 34, stateName: 'North Dakota' },
    { id: 35, stateName: 'Ohio' },
    { id: 36, stateName: 'Oklahoma' },
    { id: 37, stateName: 'Oregon' },
    { id: 38, stateName: 'Pennsylvania' },
    { id: 39, stateName: 'Rhode Island' },
    { id: 40, stateName: 'South Carolina' },
    { id: 41, stateName: 'South Dakota' },
    { id: 42, stateName: 'Tennessee' },
    { id: 43, stateName: 'Texas' },
    { id: 44, stateName: 'Utah' },
    { id: 45, stateName: 'Vermont' },
    { id: 46, stateName: 'Virginia' },
    { id: 47, stateName: 'Washington' },
    { id: 48, stateName: 'West Virginia' },
    { id: 49, stateName: 'Wisconsin' },
    { id: 50, stateName: 'Wyoming' },
];


module.exports = states